version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
    - echo "Checking default Java version..."
    - java -version
    - echo "Installing dependencies..."
    - pip install pylint
    - echo "Downloading and setting up SonarScanner CLI..."
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip sonar-scanner-cli-5.0.1.3006-linux.zip -d /opt
    - rm sonar-scanner-cli-5.0.1.3006-linux.zip
    - export PATH=$PATH:/opt/sonar-scanner-5.0.1.3006-linux/bin
    - export SONAR_SCANNER_HOME=/opt/sonar-scanner-5.0.1.3006-linux
    # Ensure JAVA_HOME is set to use the system's java, not the bundled one which caused problems
    - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
    - echo "Creating sonar user and group..."
    - groupadd sonar || true # If group already exists, don't fail
    - useradd -r -s /bin/false -g sonar sonar || true # If user already exists, don't fail
    - chown -R sonar:sonar /opt/sonar-scanner-5.0.1.3006-linux
    - chmod -R 755 /opt/sonar-scanner-5.0.1.3006-linux
    - echo "Verifying SonarScanner version..."
    - /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -v

  pre_build:
    commands:
    - echo "Pre-build step; install project dependencies..."
    - pip install -r requirements.txt

  build:
    commands:
    - echo "Running pylint..."
    - pylint --exit-zero accounts/ main/ southern_delicious/
    - echo "Running sonar-scanner as sonar user..."
    - sudo -u sonar /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -X

  post_build:
    commands:
    - echo "Post-build steps..."
