version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - uname -m
      - echo "Installing pylint..."
      - pip install pylint
      - echo "Installing SonarScanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin

  pre_build:
    commands:
      - echo "Pre-build step; install project dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running pylint..."
      - pylint --exit-zero accounts/ main/ southern_delicious/
      - echo "Running sonar-scanner..."
      - >
        sonar-scanner
        -Dsonar.projectKey=RohithKonanRavi_southern-Delicious
        -Dsonar.organization=rohithkonanravi
        -Dsonar.sources=.
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=4dc5c635c1bcb253d4855f421850974a2b00b91a
        -Djava.home=$(pwd)/sonar-scanner-5.0.1.3006-linux/jre

  post_build:
    commands:
      - echo "Post-build steps..."
