version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Check architecture
      - uname -m
      # Update system and install OpenJDK 17
      - sudo yum update -y
      - sudo amazon-linux-extras install -y java-openjdk17
      # Set JAVA_HOME for OpenJDK 17 (Amazon Linux 2)
      - export JAVA_HOME=$(/usr/libexec/java_home -v 17)
      # Install pylint
      - echo "Installing pylint..."
      - pip install pylint
      # Download and setup SonarScanner (Make sure to use compatible version or architecture-neutral if available)
      - echo "Installing SonarScanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin

  pre_build:
    commands:
      # Install project dependencies from requirements.txt
      - echo "Pre-build step; install project dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      # Run pylint
      - echo "Running pylint..."
      - pylint --exit-zero accounts/ main/ southern_delicious/
      # Execute SonarScanner using the specified JAVA_HOME
      - echo "Running sonar-scanner..."
      - >
        sonar-scanner
        -Dsonar.projectKey=RohithKonanRavi_southern-Delicious
        -Dsonar.organization=rohithkonanravi
        -Dsonar.sources=.
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=4dc5c635c1bcb253d4855f421850974a2b00b91a
        -Djava.home=$JAVA_HOME

  post_build:
    commands:
      # Any post-build steps you have
      - echo "Post-build steps..."
