version: 0.2

env:
  variables:
    PYLINT_THRESHOLD: "3.0"

phases:
  install:
    commands:
    - yum update -y bc
    - yum install -y python3-pip bc
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install django djangorestframework pylint
    - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip
    - java -version
    - export JAVA_HOME=$(pwd)/sonar-scanner-5.0.1.3006-linux/jre
    - java -version
    - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
    - sonar-scanner --version



  pre_build:
    commands:
    - pip install -r requirements.txt
    # Runnig pylint to check errors in the code
    - pylint --exit-zero --output-format=text accounts main southern_delicious  | tee pylint_report.txt
    - PYLINT_SCORE=$(awk '/Your code has been rated at/{print $}' pylint_report.txt | cut -d'/' -f1)
    - echo "Score of pylint is:" " ${PYLINT_SCORE}"
    - |
      if (( $(echo "$PYLINT_SCORE < $PYLINT_THRESHOLD" | bc -l) )); then
        echo "Pylint score is below the threshold of $PYLINT_THRESHOLD"
        exit 1
      fi



    # Fail the build if PYLINT_SCORE is below the threshold
  build:
    commands:
    #sonar analyiss this report will be send to the sonarcloud

    - echo "successfull"
    - sonar-scanner -Dsonar.organization=rohithkonanravi -Dsonar.projectKey=RohithKonanRavi_southern-Delicious -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.python.pylint.reportPaths=pylint_report.txt


artifacts:
  files:
  - '**/*'
