version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing pylint..."
      - pip install pylint
      - echo "Installing SonarScanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
  
  pre_build:
    commands:
      - echo "Pre-build step; install project dependencies..."
      # Add commands to install any dependencies your project might have, for example:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running pylint..."
      # Replace ./src with the directory where your Python code exists
      - pylint ./src
      - echo "Running sonar-scanner..."
      # The following environment variables and scanner properties will be used by sonar-scanner
      - >
        sonar-scanner
        -Dsonar.projectKey=RohithKonanRavi_southern-Delicious
        -Dsonar.organization=rohithkonanravi
        -Dsonar.sources=./src
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=236f7a35882853a0ab27bd75d4c45a5b9c5604c6

  post_build:
    commands:
      - echo "Post-build steps..."
      # Add any commands that need to be run after the build phase
