version: 0.2

env:
  secrets-manager:
    LOGIN: prod/sonar/SD:sonartoken
    HOST: prod/sonar/SD:HOST
    Organization: prod/sonar/SD:Organization
    Project: prod/sonar/SD:Project
phases:
  install:
    runtime-versions:
      python: 3.9
      java: corretto17    
    commands:
      - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version 
      - echo Installing requirements...
      - pip install -r requirements.txt
      - pip install pylint
      - echo Installing SonarQube scanner...
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli-4.6.2.2472-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin

  pre_build:
    commands:
      - echo Running Pylint...
      - pylint --exit-zero accounts/ main/ southern_delicious/

  build:
    commands:
      - echo Running tests...
      - python manage.py test
      - echo Starting SonarQube analysis...
      - |
        sonar-scanner -X 
        -Dsonar.projectKey=$project
        -Dsonar.organization=$Organization
        -Dsonar.sources=. 
        -Dsonar.host.url=$HOST 
        -Dsonar.login=$LOGIN 


  post_build:
    commands:
      - echo Build completed on `date`
      # Add AWS Elastic Beanstalk deployment commands here

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.sonar/cache/**/*'
