version: 0.2

env:
  variables:
    LOGIN: "236f7a35882853a0ab27bd75d4c45a5b9c5604c6"
    HOST: "https://sonarcloud.io"
    ORGANIZATION: "rohithkonanravi"
    PROJECT: "RohithKonanRavi_southern-Delicious"

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.11
    commands:
      - java -version
      - pip install -r requirements.txt 
      - pip install pylint
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d /opt/sonar-scanner
      - export PATH=/opt/sonar-scanner/bin:$PATH
      - sonar-scanner -v
      - yum install -y jq  # Preferred package manager for Amazon Linux

  pre_build:
    commands:
      - pylint --exit-zero accounts/ main/ southern_delicious/

  build:
    commands:
      - python manage.py test
      - sonar-scanner -X -Dsonar.projectKey=$PROJECT -Dsonar.organization=$ORGANIZATION -Dsonar.sources=. -Dsonar.host.url=$HOST -Dsonar.login=$LOGIN -Dsonar.python.coverage.reportPaths=coverage.xml
      - sleep 5 
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT > result.json
      - cat result.json
      - jq -r '.projectStatus.status' result.json | grep -q "ERROR" && echo "Quality Gate failed" && exit 1

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'  
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.sonar/cache/**/*'
